---
- name: "{{ method }} {{ item.name }} {{ format }} {{ type }} repository"
  ansible.builtin.uri:
    url: >
      {% if method in ['POST'] %}
        {{ nexus_api_scheme }}://{{ nexus_hostname }}:{{ nexus_api_port }}/service/rest/v1/repositories/{{ format }}/{{ type }}
      {% elif method in ['PUT'] %}
        {{ nexus_api_scheme }}://{{ nexus_hostname }}:{{ nexus_api_port }}/service/rest/v1/repositories/{{ format }}/{{ type }}/{{ item.name }}
      {% else %}
        {{ nexus_api_scheme }}://{{ nexus_hostname }}:{{ nexus_api_port }}/service/rest/v1/repositories/{{ item.name }}
      {% endif %}
    method: "{{ method }}"
    validate_certs: false
    status_code: "{{ '201' if method == 'POST' else '204' }}"
    user: "{{ nexus_admin_username }}"
    password: "{{ nexus_admin_password }}"
    force_basic_auth: true
    body: "{{ item }}"
    body_format: json
  changed_when: true
