---
- name: Construct API call
  ansible.builtin.set_fact:
    api_url: >
      {% if method in ['POST'] %}
        {{ nexus_api_scheme }}://{{ nexus_hostname }}:{{ nexus_api_port }}/service/rest/v1/security/users
      {% elif method in ['PUT', 'DELETE'] %}
        {{ nexus_api_scheme }}://{{ nexus_hostname }}:{{ nexus_api_port }}/service/rest/v1/security/users/{{ item.userId }}
      {% endif %}
    api_body: >
      {% if method == 'POST' %}
        {{ item | combine({"password": nexus_default_user_password}) | to_json }}
      {% else %}
        {{ item | to_json }}
      {% endif %}
  tags: users

- name: "{{ method }} {{ item.userId }} user"
  ansible.builtin.uri:
    url: "{{ api_url }}"
    method: "{{ method }}"
    validate_certs: false
    status_code: "{{ '200' if method == 'POST' else '204' }}"
    user: "{{ nexus_admin_username }}"
    password: "{{ nexus_admin_password }}"
    force_basic_auth: true
    body: "{{ api_body }}"
    body_format: json
  changed_when: true
  tags: users
